services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
  kinvo-backend:
    container_name: kinvo-backend
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
